#!/bin/bash

urls=(
"https://linkedin.com/company/accenture"
"https://linkedin.com/company/adani-connex"
"https://linkedin.com/company/adobe"
"https://linkedin.com/company/agrigoi"
"https://linkedin.com/company/ahk-india"
"https://linkedin.com/company/akis-tech"
"https://linkedin.com/company/alimco"
"https://linkedin.com/company/amazon-web-services"
"https://linkedin.com/company/amd"
"https://linkedin.com/company/anant-raj-limited"
"https://linkedin.com/company/ansys"
"https://linkedin.com/company/anusandhan-national-research-foundation"
"https://linkedin.com/company/apna-com"
"https://linkedin.com/company/arista-networks"
"https://linkedin.com/company/asus"
"https://linkedin.com/company/australian-government"
"https://linkedin.com/company/ayushmannha"
"https://linkedin.com/company/bank-of-baroda"
"https://linkedin.com/company/bharat-electronics-limited"
"https://linkedin.com/company/bharti-airtel"
"https://linkedin.com/company/bhashini"
"https://linkedin.com/company/bill-and-melinda-gates-foundation"
"https://linkedin.com/company/birac"
"https://linkedin.com/company/blockchain-for-impact"
"https://linkedin.com/company/british-high-commission-new-delhi"
"https://linkedin.com/company/businessfrance"
"https://linkedin.com/company/c-dot"
"https://linkedin.com/company/cbc-india"
"https://linkedin.com/company/cisco"
"https://linkedin.com/company/cloudflare"
"https://linkedin.com/company/coal-india-limited"
"https://linkedin.com/company/cognizant"
"https://linkedin.com/company/corover"
"https://linkedin.com/company/cris-india"
"https://linkedin.com/company/csrbox"
"https://linkedin.com/company/datadirect-networks"
"https://linkedin.com/company/delhi-government"
"https://linkedin.com/company/delhi-metro-rail-corporation"
"https://linkedin.com/company/dell-technologies"
"https://linkedin.com/company/deloitte"
"https://linkedin.com/company/doitc"
"https://linkedin.com/company/drdo-india"
"https://linkedin.com/company/ekstep-foundation"
"https://linkedin.com/company/electronic-software-export-promotion-council"
"https://linkedin.com/company/enterprise-estonia"
"https://linkedin.com/company/ernstandyoung"
"https://linkedin.com/company/eros-innovation"
"https://linkedin.com/company/esds-software-solution-limited"
"https://linkedin.com/company/eset"
"https://linkedin.com/company/exotel"
"https://linkedin.com/company/extramarks"
"https://linkedin.com/company/fortinet"
"https://linkedin.com/company/github"
"https://linkedin.com/company/gnani-ai"
"https://linkedin.com/company/google"
"https://linkedin.com/company/government-of-assam"
"https://linkedin.com/company/government-of-bihar"
"https://linkedin.com/company/government-of-chhattisgarh"
"https://linkedin.com/company/government-of-goa"
"https://linkedin.com/company/government-of-karnataka"
"https://linkedin.com/company/government-of-maharashtra"
"https://linkedin.com/company/government-of-manipur"
"https://linkedin.com/company/government-of-meghalaya"
"https://linkedin.com/company/government-of-tajikistan"
"https://linkedin.com/company/government-of-tamil-nadu"
"https://linkedin.com/company/government-of-tripura"
"https://linkedin.com/company/government-of-uttar-pradesh"
"https://linkedin.com/company/government-of-uttarakhand"
"https://linkedin.com/company/government-of-west-bengal"
"https://linkedin.com/company/gujarat-informatics-ltd"
"https://linkedin.com/company/hcltech"
"https://linkedin.com/company/hewlett-packard-enterprise"
"https://linkedin.com/company/hp"
"https://linkedin.com/company/ibm"
"https://linkedin.com/company/iconova"
"https://linkedin.com/company/iitm-pune"
"https://linkedin.com/company/indian-army"
"https://linkedin.com/company/indian-navy"
"https://linkedin.com/company/infosys"
"https://linkedin.com/company/intel-corporation"
"https://linkedin.com/company/intellect_design_arena"
"https://linkedin.com/company/international-solar-alliance"
"https://linkedin.com/company/italian-trade-agency"
"https://linkedin.com/company/jetro"
"https://linkedin.com/company/karmayogi-bharat"
"https://linkedin.com/company/kerala-state-it-mission"
"https://linkedin.com/company/kyndryl"
"https://linkedin.com/company/lenovo"
"https://linkedin.com/company/lexlegis-ai"
"https://linkedin.com/company/linkedin"
"https://linkedin.com/company/lt-vyoma"
"https://linkedin.com/company/mastercard"
"https://linkedin.com/company/meganet"
"https://linkedin.com/company/meity-in"
"https://linkedin.com/company/meta"
"https://linkedin.com/company/microsoft"
"https://linkedin.com/company/ministry-of-ayush"
"https://linkedin.com/company/ministry-of-earth-sciences"
"https://linkedin.com/company/ministry-of-education-government-of-india"
"https://linkedin.com/company/ministry-of-panchayati-raj"
"https://linkedin.com/company/ministry-of-rural-development"
"https://linkedin.com/company/ministry-of-skill-development-and-entrepreneurship-india"
"https://linkedin.com/company/ministry-of-steel"
"https://linkedin.com/company/mpsedc"
"https://linkedin.com/company/neevcloud"
"https://linkedin.com/company/netherlands-embassy-india"
"https://linkedin.com/company/netweb-technologies-india-ltd"
"https://linkedin.com/company/neysa-networks"
"https://linkedin.com/company/npci"
"https://linkedin.com/company/nvidia"
"https://linkedin.com/company/odisha-computer-application-centre"
"https://linkedin.com/company/openai"
"https://linkedin.com/company/plivo"
"https://linkedin.com/company/power-grid-corporation-of-india"
"https://linkedin.com/company/prisma-ai"
"https://linkedin.com/company/punjab-infotech"
"https://linkedin.com/company/qhala"
"https://linkedin.com/company/qualcomm"
"https://linkedin.com/company/railtelindia"
"https://linkedin.com/company/razorpay"
"https://linkedin.com/company/rec-limited"
"https://linkedin.com/company/red-hat"
"https://linkedin.com/company/redington-india"
"https://linkedin.com/company/reliance-jio"
"https://linkedin.com/company/salesforce"
"https://linkedin.com/company/sarvam-ai"
"https://linkedin.com/company/schneider-electric"
"https://linkedin.com/company/serbian-government"
"https://linkedin.com/company/servicenow"
"https://linkedin.com/company/sify-technologies"
"https://linkedin.com/company/simplismart"
"https://linkedin.com/company/state-bank-of-india"
"https://linkedin.com/company/super-micro-computer"
"https://linkedin.com/company/swiss-embassy-india"
"https://linkedin.com/company/tata-consultancy-services"
"https://linkedin.com/company/tcg-digital"
"https://linkedin.com/company/tech-mahindra"
"https://linkedin.com/company/the-lego-group"
"https://linkedin.com/company/thoughtworks"
"https://linkedin.com/company/tsia"
"https://linkedin.com/company/turiyam"
"https://linkedin.com/company/uidai"
"https://linkedin.com/company/velankani-information-systems"
"https://linkedin.com/company/vertiv"
"https://linkedin.com/company/vvdn-technologies"
"https://linkedin.com/company/wadhwani-ai"
"https://linkedin.com/company/wipro"
"https://linkedin.com/company/world-food-programme"
"https://linkedin.com/company/yotta-infrastructure"
"https://linkedin.com/company/zoho"
)

echo "=== CHECKING ${#urls[@]} LinkedIn URLs ==="
echo ""

invalid_count=0
valid_count=0

for url in "${urls[@]}"; do
  slug=$(echo "$url" | sed 's|https://linkedin.com/company/||')
  
  http_code=$(curl -o /dev/null -s -w "%{http_code}" -L \
    --max-time 10 \
    -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
    "$url" 2>/dev/null)
  
  if [ "$http_code" -eq 404 ] || [ "$http_code" -eq 0 ]; then
    echo "INVALID ($http_code): $slug"
    ((invalid_count++))
  elif [ "$http_code" -ge 400 ]; then
    echo "SUSPECT ($http_code): $slug"
    ((invalid_count++))
  else
    echo "VALID ($http_code): $slug"
    ((valid_count++))
  fi
  
  sleep 0.3
done

echo ""
echo "=== SUMMARY ==="
echo "Valid: $valid_count"
echo "Invalid/Suspect: $invalid_count"
echo "Total checked: ${#urls[@]}"
